run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 10
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - typecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
